/**
 * Preview generation API route
 * POST /api/preview - Generate quick preview of STL design
 */

import { type NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { promises as fs } from 'fs';
import { stlFileManager, openscadExecutor } from '@/lib/openscad';
import { withRateLimit } from '@/lib/api/rateLimit';
import { withErrorHandler } from '@/lib/api/errors';
import { logger } from '@/lib/logger';

// Request validation schema (similar to generate route but for preview)
const PreviewRequestSchema = z.object({
  svg: z.string().min(1, 'SVG content is required'),
  config: z.object({
    gridUnitsX: z.number().int().min(1).max(10),
    gridUnitsY: z.number().int().min(1).max(10),
    binHeight: z.number().min(7),
    cutoutDepth: z.number().min(3),
    cutoutPadding: z.number().min(0).default(2),
    cutoutOffsetX: z.number().default(0),
    cutoutOffsetY: z.number().default(0),
    wallThickness: z.number().min(1).default(2),
    baseType: z.enum(['solid', 'magnet', 'screw', 'magnet_screw']).default('magnet'),
    lipStyle: z.enum(['normal', 'reduced', 'none']).default('normal'),
    cornerRadius: z.number().optional().default(0),
    taperAngle: z.number().optional().default(0),
  }),
});

/**
 * POST handler for preview generation
 */
async function previewHandler(request: NextRequest): Promise<NextResponse> {
  const startTime = Date.now();

  try {
    // Parse and validate request
    const body = await request.json();
    const validation = PreviewRequestSchema.safeParse(body);

    if (!validation.success) {
      const issues = validation.error.issues;
      logger.warn('Invalid preview request', { errors: issues });
      return NextResponse.json(
        { error: 'Invalid request', details: issues },
        { status: 400 }
      );
    }

    const { svg, config } = validation.data;

    // Create temporary job paths for preview
    const paths = await stlFileManager.createJobPaths();

    try {
      // Write SVG file
      await fs.writeFile(paths.svgPath, svg, 'utf-8');

      // Generate simplified OpenSCAD script for preview
      const scadContent = generatePreviewScript(paths.svgPath, config);
      await fs.writeFile(paths.scadPath, scadContent, 'utf-8');

      // Generate preview with lower quality settings for speed
      const previewResult = await openscadExecutor.preview(
        paths.scadPath,
        paths.previewPath,
        {
          imgsize: '600,450',
          timeout: 15000, // 15 second timeout
        }
      );

      if (!previewResult.success || !previewResult.previewPath) {
        logger.error('Preview generation failed', {
          error: previewResult.error,
          stderr: previewResult.stderr,
        });
        throw new Error(previewResult.error || 'Preview generation failed');
      }

      // Read the generated preview image
      const previewBuffer = await fs.readFile(previewResult.previewPath);

      const renderTime = Date.now() - startTime;

      logger.info('Preview generated', {
        jobId: paths.jobId,
        renderTime,
        size: previewBuffer.length,
      });

      // Clean up temporary files after a short delay
      setTimeout(() => {
        stlFileManager.cleanupJob(paths.jobId).catch((err) => {
          logger.error('Failed to cleanup preview job', { jobId: paths.jobId, error: err });
        });
      }, 5000);

      // Return PNG image
      return new NextResponse(previewBuffer, {
        status: 200,
        headers: {
          'Content-Type': 'image/png',
          'Cache-Control': 'private, max-age=300', // Cache for 5 minutes
          'X-Render-Time': renderTime.toString(),
        },
      });
    } catch (error) {
      // Clean up on error
      await stlFileManager.cleanupJob(paths.jobId);
      throw error;
    }
  } catch (error) {
    logger.error('Preview generation error', {
      error: error instanceof Error ? error.message : 'Unknown error',
      duration: Date.now() - startTime,
    });

    return NextResponse.json(
      {
        error: 'Preview generation failed',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

/**
 * Generate simplified OpenSCAD script for preview
 * (lower quality settings for faster rendering)
 */
function generatePreviewScript(svgPath: string, config: z.infer<typeof PreviewRequestSchema>['config']): string {
  return `
// Gridfinity Preview - Generated by Snap Caddy
// Simplified for faster rendering

// Basic parameters
gridx = ${config.gridUnitsX};
gridy = ${config.gridUnitsY};
bin_height = ${config.binHeight};
cutout_depth = ${config.cutoutDepth};
wall_thickness = ${config.wallThickness};

// Grid unit size
grid_unit = 42;
base_height = 5;

// Lower quality for preview
$fn = 24; // Reduced from 64 for speed

// Main structure
difference() {
  // Simple bin body
  translate([0, 0, base_height / 2])
  cube([
    gridx * grid_unit,
    gridy * grid_unit,
    bin_height
  ], center = true);

  // Cutout from SVG
  translate([0, 0, bin_height - cutout_depth])
  linear_extrude(height = cutout_depth + 1)
  offset(delta = ${config.cutoutPadding})
  import("${svgPath}", center = true, dpi = 96);

  // Hollow interior (simplified)
  translate([0, 0, base_height + wall_thickness])
  cube([
    gridx * grid_unit - wall_thickness * 2,
    gridy * grid_unit - wall_thickness * 2,
    bin_height
  ], center = true);
}
`;
}

// Apply middleware: rate limiting -> error handling
export const POST = withRateLimit(
  withErrorHandler(previewHandler),
  {
    maxRequests: 20, // More generous for previews
    windowMs: 60000, // 1 minute
  }
);

// Export runtime configuration
export const runtime = 'nodejs';
export const maxDuration = 15; // 15 seconds max for preview
