/**
 * Gridfinity Custom Cutout Bin Template
 * Generated by Snap Caddy - {{TIMESTAMP}}
 *
 * This template creates a Gridfinity-compatible bin with a custom SVG cutout
 * using the gridfinity_extended_openscad library.
 */

// Include Gridfinity library
use <gridfinity-rebuilt-utility.scad>
use <gridfinity-rebuilt-bins.scad>

// === Configuration Parameters ===

// Grid dimensions (1 unit = 42mm)
grid_x = {{GRID_X}};
grid_y = {{GRID_Y}};

// Bin height in mm
bin_height = {{BIN_HEIGHT}};

// Cutout configuration
cutout_depth = {{CUTOUT_DEPTH}};
svg_file_path = "{{SVG_FILE_PATH}}";

// Wall and base configuration
wall_thickness = {{WALL_THICKNESS}};
base_thickness = {{BASE_THICKNESS}};

// Base style (0=solid, 1=magnet, 2=screw, 3=magnet_screw)
base_style = {{BASE_STYLE}};

// Lip style (0=normal, 1=reduced, 2=none)
lip_style = {{LIP_STYLE}};

// Advanced options
corner_radius = {{CORNER_RADIUS}};

// Padding around cutout
padding_top = {{PADDING_TOP}};
padding_bottom = {{PADDING_BOTTOM}};
padding_left = {{PADDING_LEFT}};
padding_right = {{PADDING_RIGHT}};

// === Calculated Values ===

// Calculate total bin dimensions
bin_width = grid_x * 42;
bin_depth = grid_y * 42;

// Calculate cutout dimensions based on bin size and padding
cutout_width = bin_width - wall_thickness * 2 - padding_left - padding_right;
cutout_height = bin_depth - wall_thickness * 2 - padding_top - padding_bottom;

// Calculate cutout position (centered with padding offset)
cutout_x = (padding_left - padding_right) / 2;
cutout_y = (padding_top - padding_bottom) / 2;

// === Module Definitions ===

/**
 * Creates the base Gridfinity bin structure
 */
module gridfinity_base_bin() {
    gridfinityInit(grid_x, grid_y, height(bin_height), 0, lip_style) {
        cutEqual(n_divx=1, n_divy=1, style_tab=1, enable_scoop=false);
    }
    gridfinityBase(grid_x, grid_y, bin_height, 0, base_style);
}

/**
 * Creates the SVG cutout shape
 */
module svg_cutout() {
    translate([cutout_x, cutout_y, bin_height - cutout_depth]) {
        linear_extrude(height = cutout_depth + 1) {
            scale([cutout_width / 100, cutout_height / 100, 1]) {
                import(svg_file_path, center=true, dpi=96);
            }
        }
    }
}

/**
 * Main module - creates bin with custom cutout
 */
module gridfinity_custom_bin() {
    difference() {
        gridfinity_base_bin();
        svg_cutout();
    }
}

// === Render ===

gridfinity_custom_bin();
